### Variables 
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlOTBhNzIwYjgxZjcwMTg4NDQwNmMwZCIsImlhdCI6MTU4NjUzODc4NywiZXhwIjoxNTg5MTMwNzg3fQ.m6NybPpchfA9bdA0XIMS-Mme96SJGw1kyn_exnw9m1M


### Register User
POST http://localhost:5000/auth/login HTTP/1.1
Content-Type: application/json

{
    "username":"Jack",
    "email":"jack@gmail.com",
    "password":"12345678"
}

### Get Bookmarks
GET http://localhost:5000/bookmark HTTP/1.1
Authorization: Bearer {{token}}


### Delete Bookmark
DELETE http://localhost:5000/bookmark/5e90a81084ede818eb2d13fd HTTP/1.1
Authorization: Bearer {{token}}

### Bookmark Movie 
POST http://localhost:5000/bookmark HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 70525,
    "title": "Thor: Ragnarok",
    "year": 2017,
    "rating": 7.9,
    "genres": ["Action", "Adventure", "Comedy", "Fantasy", "Sci-Fi"],
    "language": "English",
    "cover": "https://yts.mx/assets/images/movies/thor_ragnarok_2017/medium-cover.jpg",
    "user":"5e90a720b81f701884406c0d"
  }